post_install() {
    echo -e "\n** This application is coming from ArcoLinux."
    echo -e "** It is meant to be working on that system."
    echo -e "** By renaming the tool from ArcoLinux Tweak Tool to"
    echo -e "** ArchLinux Tweak Tool our aim is to broaden our scope."
    echo -e "** Following distros are supported."
    echo
    echo -e "** ArcoLinux"
    echo -e "** Arch Linux"
    echo -e "** Carli"
    echo -e "** Alci"
    echo -e "** Ariser"
    echo -e "** EndeavourOS"
    echo -e "** Garuda"
	echo -e "** Manjaro"
    echo -e "** RebornOS"
    echo -e "** Archcraft"
    echo -e "** CachyOS"
    echo -e "** Archman"
    echo -e "** Biglinux"
    echo -e "** Artix"
    echo -e "** ParchLinux"
    echo -e "** StormOS"
    echo -e "** Mabox"
    echo -e "** ArchBang"
    echo -e "** Crystal Linux"
    echo -e "** Liya"
    echo -e "** Bluestar Linux"
    echo -e "** Calam-Arch-Installer"
    echo
    echo -e "** At a later stage we can add other Arch based distros.\n"
}

post_upgrade() {
    post_install
}



